# -*- coding: utf-8 -*-
"""Get Returns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n3JIbLVYMDEYbQrjEHFeJQ8M7gIUS5f7
"""

import yfinance as yf
import pandas as pd

def get_stock_data(symbol):
    data = yf.download(symbol)
    prices = data['Close']
    return prices

def YahooData2returns(YahooData):
    adj_close = YahooData['Close']

    pricevec = adj_close.values

    n = len(pricevec)
    ratiovec = pricevec[1:n] / pricevec[:n-1]
    returns = ratiovec - 1
    return returns

symbol = 'GS'
data = yf.download(symbol)
returns = YahooData2returns(data)
print(returns)