# -*- coding: utf-8 -*-
"""VaR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N1S1BkbXDwQ6qy0Qmx6usnUroiV2RTEQ
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

def VaR(r, confidence, principal=1):
    plt.hist(r, bins=50, alpha=0.75)
    plt.show()

    alpha = 1 - confidence

    out = np.percentile(r, alpha * 100)

    out = abs(out)

    out = principal * out

    return out

r = np.random.normal(0.05, 0.03, 1000000)
probability2SD = norm.cdf(2)
my_confidence = probability2SD
my_var = VaR(r, my_confidence)
print(np.round(my_var, 2) == 0.01)